# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 02:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='emotion',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 5, 2, 35, 41, 637173, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
