# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20160605_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('like', 'Like'), ('reply', 'Reply'), ('registration', 'Registration')], max_length=50),
        ),
    ]
